# Generated by Django 4.0.4 on 2022-05-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('1', 'IT DEPT'), ('2', 'SALES'), ('3', 'PRINT'), ('4', 'EBM'), ('5', 'ISB'), ('6', 'IM'), ('7', 'QC'), ('8', 'PLANNING'), ('9', 'DEVELOPMENT'), ('10', 'TOOLROOM'), ('11', 'MAINTENENCE'), ('12', 'HR'), ('13', 'PURCHASING'), ('14', 'MARKETING'), ('15', 'OTHER')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_member', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now=True)),
                ('issue_summary', models.CharField(max_length=70)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('0', 'Not Started'), ('1', 'In Progress'), ('2', 'Finished')], max_length=1)),
                ('staff_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stf_assigned', to='app.staff')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stf_member', to='app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('computer_id', models.CharField(max_length=60)),
                ('serial_no', models.CharField(max_length=20)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
        ),
    ]
